<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Wallet.Worker-6168669e-8cf9-4cfb-83f0-68d97dc8d545</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wallet.Application\Wallet.Application.csproj" />
    <ProjectReference Include="..\Wallet.Infrastructure\Wallet.Infrastructure.csproj" />
  </ItemGroup>
</Project>
